# Generated by Django 3.1.7 on 2021-03-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investment',
            name='return_capital',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='maximum',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='minimum',
            field=models.FloatField(),
        ),
    ]
