# Generated by Django 3.1.7 on 2021-03-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20210327_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
