# Generated by Django 3.1.7 on 2021-03-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20210327_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='capital_return',
            field=models.BooleanField(default=True),
        ),
    ]
