# Generated by Django 3.1.7 on 2021-03-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_capital_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoiAmount',
            fields=[
                ('roi_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('minimum', models.DecimalField(decimal_places=3, max_digits=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.plan')),
            ],
        ),
    ]
