# Generated by Django 3.1.7 on 2021-03-30 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_roiamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='roiamount',
            name='maximum',
            field=models.DecimalField(decimal_places=3, max_digits=12),
            preserve_default=False,
        ),
    ]
