# Generated by Django 3.1.7 on 2021-03-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_roiamount_maximum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roiamount',
            old_name='maximum',
            new_name='percent',
        ),
        migrations.RemoveField(
            model_name='roiamount',
            name='minimum',
        ),
    ]
