# Generated by Django 3.1.7 on 2021-04-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20210330_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='interest',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='plan',
            name='maximum',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='plan',
            name='minimum',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
