# Generated by Django 3.1.6 on 2021-04-05 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_auto_20210404_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
