# Generated by Django 3.1.7 on 2021-03-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='action',
            name='debug_balance',
            field=models.FloatField(),
        ),
    ]
