# Generated by Django 3.1.7 on 2021-03-28 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210328_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trx_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trx_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
